name: ci

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset windows-x64

      - name: Build
        run: cmake --build "build/windows-x64" --config Release

      - name: Test
        run: ctest -C Release --test-dir build/windows-x64 --output-on-failure
